:bug: Check if the GITHUB_STEP_SUMMARY is set in order to determine if an error occurred

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -36,8 +36,12 @@ runs:
         sudo apt-get clean
     - name: Verify project
       run: |
-        set +e
         verify-cmsis-example-sdk verify --project-dir ${{ inputs.project-directory }} --project-path ${{ inputs.project-file }} --out-dir out --api-key ${{ inputs.API_TOKEN }} --log-error 2
+        # The status code is not being reported correctly and the action is reportedly exiting with 0 when all reproductions of the run on dev machines correctly exit with a status of 1. Therefore we will explicitly check if the error summary was created and exit 1 if it was
+        if [ -s $GITHUB_STEP_SUMMARY ]; then
+          echo "::error::Verification of CMSIS project failed"
+          exit 1
+        fi
       shell: bash
     - name: Upload any artifacts
       uses: actions/upload-artifact@v4
